version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app 
    ports:
      - "42069:42069"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/clusters/redisdata:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis ping"]
      interval: 5s
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  app:
    image: b64viewer
    build: .
    expose:
      - 420
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10